export const MAIN_LISTS = "MAIN_LISTS";
export const MENTOR_LISTS = "MENTOR_LISTS";
export const MENTEE_LISTS = "MENTEE_LISTS";
export const GET_USER = "GET_USER";
export const GET_MENTOR = "GET_MENTOR";
export const GET_MENTEE = "GET_MENTEE";
export const MENTOR_DIARIES = "MENTOR_DIARIES";
export const MENTEE_DIARIES = "MENTEE_DIARIES";
export const DIARY = "DIARY";


export const IS_LOGGED = "ISLOGGED";
export const AUTH_CHECK = "AUTH_CHECK";

export const OPENAPI_MACHINE = "OPENAPI_MACHINE";
export const OPENAPI_SPECIALCROPS = "OPENAPI_SPECIALCROPS";
export const OPENAPI_DICTIONARY = "OPENAPI_DICTIONARY";
export const OPENAPI_EMPTYHOUSES = "OPENAPI_EMPTYHOUSES";


